### ISSUE TITLE
Do you use Super Ray method in this repository?

### ISSUE THREAD

**Issue by jackykongfz** [PinocchioYS/realtime_occupancy_mapping#1]
I have run this program successfully, but when I read the code I find that it may just use the culling region method. So I want to ask if you use SuperRay method in this program ?

**Comment by PinocchioYS** [comment]
The simplest solution to use the SuperRay method is to change the update function `insertPointCloudRays()` into [`insertSuperRayCloudRays()`](https://github.com/PinocchioYS/SuperRay/blob/191baca4e7d540781062bd9764d63e70e4f68b60/gridmap3D/include/gridmap3D_cullingregion/CullingRegionGrid3D.h#L78) in the example code.
https://github.com/PinocchioYS/realtime_occupancy_mapping/blob/fbadac9c23f69370dd6e40044ed1386f8f9d9cc0/src/realtime_occupancy_mapping.cpp#L62 Then, the map is updated by both SuperRay and CullingRegion methods, since this example utilizes CullingRegionGrid3D class.

If you want to use the SuperRay method without CullingRegion, you need to use the [SuperRayGrid3D](https://github.com/PinocchioYS/SuperRay/blob/191baca4e7d540781062bd9764d63e70e4f68b60/gridmap3D/include/gridmap3D_superray/SuperRayGrid3D.h) class instead of [CullingRegionGrid3D](https://github.com/PinocchioYS/SuperRay/blob/191baca4e7d540781062bd9764d63e70e4f68b60/gridmap3D/include/gridmap3D_cullingregion/CullingRegionGrid3D.h). It may require changing a few lines of the example code.

**Comment by jackykongfz** [comment]
Thanks! It works

**Comment by maomao0220** [comment]
when i change the update function insertPointCloudRays() into insertSuperRayCloudRays(), what is the "threshold"?
    virtual void insertSuperRayCloudRays(const Pointcloud& scan, const point3d& origin, const int threshold);

**Comment by maomao0220** [comment]
when i change the update function insertPointCloudRays() into insertSuperRayCloudRays(), what is the "threshold"?
virtual void insertSuperRayCloudRays(const Pointcloud& scan, const point3d& origin, const int threshold);
 @PinocchioYS @jackykongfz

**Comment by maomao0220** [comment]
您好，改成insertSuperRayCloudRays()函数时，具体怎么设置参数threshold？threshold代表的是什么意思？
@PinocchioYS @jackykongfz

**Comment by PinocchioYS** [comment]
The 'threshold' of the insertSuperRayCloudRays() function determines whether our library converts that the input point rays into super-rays based on whether the point rays are assigned to the same voxel. 
Converting to super-rays does not guarantee improved update speed in all cases, so the threshold serves as a simple option to control performance improvement. 
If the number of point rays assigned to the same voxel is less than the threshold, the update function performs the same process to each voxel as insertPointCloudRays().
